#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'git'
cookbook 'apache2'
cookbook 'mysql'
cookbook 'php'
cookbook 'memcached'

cookbook "drush",
  :git => "https://github.com/msonnabaum/chef-drush.git",
  :ref => "master"

# cookbook 'chef-client'

